stages:

  - build
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  MW_REG_VAR: "$CI_REGISTRY_IMAGE/malware-repository:$CI_COMMIT_REF_NAME"

contain_build:
  stage: build
  script:
    - docker build -f docker/Dockerfile -t $MW_REG_VAR .
    - docker push $MW_REG_VAR

test_repo:
  stage: test
  script:
    - docker pull $MW_REG_VAR
    - docker tag $MW_REG_VAR polyswarm/malware-repository
    - docker-compose -f docker/docker-compose.yml -f docker/test.yml up --abort-on-container-exit --force-recreate




# todo push to local docker reg on test passing
